name: Acquisitionn
description: |
      "Do you have any request related to Traffic and Leads Acquisition? We can help. If related to Paid Channels (Google, Facebook or LinkedIn ads), please use the temporary Notion workspace."
labels: "acquisition"
assignees: romanepour
body:
  - type: dropdown
    attributes:
      label: Region
      description: For which region/team are you associated?
      options:
        - APAC
        - CANADA
        - CHINA
        - DACH
        - FRANCE
        - GERMANY
        - LATAM BR
        - LATAM SSC
        - MEA
        - NE
        - NECH
        - Online
        - SE
        - UK
        - Global Marketing team
        - Data Team
        - Engineering Team
        - S&A Team
    validations:
      required: true
