name: Acquisitionn
description: |
      Do you have any request related to Traffic and Leads Acquisition? We can help. If related to Paid Channels (Google, Facebook or LinkedIn ads), please use the temporary Notion workspace.
labels: "acquisition"
assignees: romanepour
body:
  - type: dropdown
    attributes:
      label: Region
      description: For which region/team are you associated?
      options:
        - APAC
        - CANADA
        - CHINA
        - DACH
        - FRANCE
        - GERMANY
        - LATAM BR
        - LATAM SSC
        - MEA
        - NE
        - NECH
        - Online
        - SE
        - UK
        - Global Marketing team
        - Data Team
        - Engineering Team
        - S&A Team
    validations:
      required: true
  - type: textarea
    attributes:
      label: Role
      description: What is your role at Le Wagon?
      placeholder: ## Marketing Manager, City Manager, Sales & Admission Manager, E&C Manager etc.
      value:
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Topic associated with your request
      options:
        - "SEO"
        - "Tracking"
        - "Referral"
        - "Google Analytics"
        - "Acquisition Dashboard/Data"
        - "Other"
    validations:
      required: true
