name: Marketing data or tracking-related Request
description: You need marketing data related to your scope or market ? Or a request related to GA4 or GTM ?
labels: ["marketing", "data-request"]
assignees : mjtorresloosli
body:
  - type: markdown
    attributes:
      value: |
        You need marketing data related to your scope or market ? Do you have a requests related to GA4 / GTM ?
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: |
        - Please describe what you are trying to achieve, which hypothesis you want to test against Data. Include the source you are thinking of (Hubspot, Kitt, etc.), the expected outcome (information, visuals, dashboard) and maximun context.
        - If related to GA4 or GTM, explain what you need to check / implement, and provide the necessary information if set up is need
  - type: dropdown
    id: recurrence
    attributes:
      label: Recurrence
      description: Is it a one-off or do you need this data every month for Reporting?
      options:
        - One-off
        - Quarterly
        - Monthly
        - Daily
    validations:
      required: true
  - type: dropdown
    id: business_unit
    attributes:
      label: Business Unit
      description: The request is emitted from which Le Wagon department?
      options:
        - Engineering
        - Finance
        - Marketing & Growth
        - Operations
        - Outcomes
        - Sales & Admissions
        - Content
        - New Product
        - For Business
    validations:
      required: true
  - type: dropdown
    id: lewagon_country
    attributes:
      label: Le Wagon Country
      description: The request is emitted from which Le Wagon country?
      options:
        - Argentina
        - Australia
        - Belgium
        - Brazil
        - Chile
        - China
        - England
        - France
        - Germany
        - Global
        - Indonesia
        - Italy
        - Mexico
        - Netherlands
        - Portugal
        - Singapore
        - Spain
        - Switzerland
        - United Kingdom
    validations:
      required: true 
