name: Marketing data or tracking Request
description: Question, visual or dashboard / tracking in GA4 / GTM set up
labels: ["marketing", "data-request"]
assignees : 
  - mjtorresloosli

body:
  - type: dropdown
    id: request
    attributes:
      label: Request
      description: What do you need
      options:
        - Marketing insights in the form of a visual or a dashboard
        - Information or request regarding www tracking (GA4 / GTM)
    validations:
      required: true

    - type: textarea
    id: goal
    attributes:
      label: Goal
      description: |
        What you are trying to achieve, which hypothesis you want to test against Data.

      - type: textarea
    id: details
    attributes:
      label: In details
      description: |
        Which data you would like to get your hands on. Mention which source you think might be useful (Hubspot, Kitt, etc.) 
        and if you already have access to a similar source (Blazer, Connected Sheet), include some URLs too to give us maximum context.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
