name: Marketing - Other Requests
description: You need technical support on marketing tools, request related to new offers or specific to B2B.
labels: ["team/growth🚀"]
assignees : mjtorresloosli
body:
- type: markdown
    attributes:
      value: |
        If you have a request about 
          - Marketing tools such as: HubSpot landing pages and modules, Webflows and Mini sites (Start, Rewards, Alternance…), marketing automations or Typeform,
          - Information on our new offers or go-to-market such as: Persona, Channels, Content or Initiatives or,
          - B2B for the enrichment of contact/companies or the creation of prospect lists for outbound (call or mailing) campaigns,
        then select the correct option below:
- type: dropdown
    id: type_request
    attributes:
        label: Type of request:
    options:
        - Marketing tools
        - Go To Market / New Product
        - B2B
    validations:
    required: true   
