name: "Marketing - Other Requests"
description: You need technical support on marketing tools, request related to new offers or specific to B2B.
labels: 
  - "team/growth🚀"
assignees : 
  - mjtorresloosli
body:
- type: markdown
  attributes:
    value: |
        If you have a request about, 
        - Marketing tools such as: HubSpot landing pages and modules, Webflows and Mini sites (Start, Rewards, Alternance…), 
        - Marketing automations or Typeform,Information on our new offers or go-to-market such as: Persona, Channels, Content or Initiatives or, 
        - B2B for the enrichment of contact/companies or the creation of prospect lists for outbound (call or mailing) campaigns,
        Then, select the correct option below.
- type: dropdown
  id: typerequest
  attributes:
    label: Type of request
    options:
      - Marketing tools
      - Go To Market / New Product
      - B2B
  validations:
    required: true
- type: textarea
  id: context
  attributes:
    label: Context
    description: |
      Please describe as detailed as possible the context of your request: what’s the current situation? What are you doing ? How?
- type: textarea
  id: goal
  attributes:
    label: Goal
    description: |
      - What is your goal? Is there something not working? What’s the impact on your work and what you try to achieve? 
      - Provide exemples, screenshot and/or URLs to make sure we understand your request.
