name: "Marketing - Other Requests"
description: You need technical support on marketing tools, request related to new offers or specific to outbound.
labels: 
  - "team/growth🚀"
assignees : 
  - mjtorresloosli
body:
- type: markdown
  attributes:
    value: |
        Your request is about about 
        - Marketing tools such as: HubSpot landing pages and modules, Webflows and Mini sites (Start, Rewards, Alternance…), Marketing automations or Typeform,
        - Information on new offers or go-to-market such as: Persona, Channels, Content or Initiatives or, 
        - Outbound marketing for the enrichment of contact/companies data or the creation of prospect lists (call or mailing) campaigns,
        Then, select the correct option below.
- type: dropdown
  id: typerequest
  attributes:
    label: Type of request
    options:
      - Marketing tools
      - Go To Market / New Product
      - Outbound Marketing
      - Other
  validations:
    required: true
- type: textarea
  id: context
  attributes:
    label: Context
    description: |
      Please describe as detailed as possible the context of your request: 
      - What are you doing ?
      - What’s the current situation? 
  validations:
    required: true
- type: textarea
  id: goal
  attributes:
    label: Goal
    description: |
      - What is your goal? Is there something not working? What’s the impact on your work and what you try to achieve? 
      - Provide exemples, screenshot and/or URLs to make sure we understand your request.
  validations:
    required: true
- type: textarea
  id: request
  attributes:
    label: Request
    description: |
      What do you need from Marketing Team or how do you think we can support your request? 
  validations:
    required: true
- type: dropdown
  id: lewagon_region
  attributes:
    label: Le Wagon Region
    description: What is your Region ?
    options:
      - APAC
      - Brazil
      - France
      - Germany
      - LATAM SSC
      - NECH
      - Global
      - Southern Europe
      - UK
  validations:
   required: true 
